# Generated by Django 4.2.11 on 2024-03-24 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker_1_db', '0003_alter_books_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published_date',
            field=models.DateField(verbose_name=models.DateField(default=datetime.datetime(2019, 7, 10, 0, 0))),
        ),
    ]
